### ISSUE TITLE
Suggestion: Replace Visual Studio Code with VSCodium

### ISSUE THREAD

**Issue by JulianWebb** [love2d-community/awesome-love2d#126]
Currently under IDEs, one of the suggestions is Visual Studio Code (VSCode) by Microsoft.

Now I know it will be a point of contention, but I believe that VSCode should be replaced with [VSCodium](https://github.com/VSCodium/vscodium) on the list because VSCodium is a FLOSS version of VSCode which removes Microsoft's branding/telemetry/licensing from the IDE. It offers the same features as VSCode, just not any of the spyware baggage.

**Comment by JanWerder** [comment]
Well, this is more politics than software development, but I always think that it's worth explaining your reasoning. I think that this is not a good idea:

- VSCodium is a repo that is maintained by basically one person, which is not ideal.
- VSCodium has the same MIT license that VSCode has, so there is really no gain in the whole FLOSS department
- VSCodium disables telemetry and crash reporting, which can easily be done in the [settings](https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-telemetry-reporting) manually
- The whole removing the "branding" thing, is just replacing the icon, which isn't even working properly [at the moment](https://github.com/VSCodium/vscodium/issues/67)

Overall I don't think that VSCodium adds anything of value.

**Comment by rm-code** [comment]
IMO if anything VSCodium should be listed as an alternative - not as a replacement.

After all, it is the user's decision wether they care about branding/telemetry/etc. - not ours.

**Comment by krischamp** [comment]
it's allways a personal choice to use FLOSS software

**Comment by JanWerder** [comment]
Please explain to me, how [VSCodium](https://github.com/VSCodium/vscodium) is more FLOSS software than VS Code itself.

**Comment by entepe85** [comment]
> Please explain to me, how [VSCodium](https://github.com/VSCodium/vscodium) is more FLOSS software than VS Code itself.

VSCodium binaries are released under MIT license, as is the original source code in [Microsofts repository](https://github.com/Microsoft/vscode). The binary builds of Visual Studio Code, however, are licensed under a proprietary license which the users have to agree to before downloading them so they are - by definition - not FLOSS.
