### ISSUE TITLE
Add Push library

### ISSUE THREAD

**Issue by nik1082** [love2d-community/awesome-love2d#133]
It's a super simple resolution-handling library that allows one to create games with a fixed resolution.
[https://github.com/Ulydev/push](https://github.com/Ulydev/push)

**Comment by JanWerder** [comment]
I think push was removed some time back, I re-added it for now:
https://github.com/love2d-community/awesome-love2d/commit/a98692c7657c25adf2ae8ebaa2b4cc954d94aed7

**Comment by D0NM** [comment]
I use Push still. Why not?
