### ISSUE TITLE
Please Add Clove

### ISSUE THREAD

**Issue by YoungNeer** [love2d-community/awesome-love2d#142]
> **100 lines of code vs 1 line of clove**. Which is better? You decide.

That's the punchline of clove. clove makes both importing assets and requiring libraries super easy. you could call it a _loader_ library

Here's a link to clove: https://github.com/YoungNeer/lovelib/tree/master/clove

**Comment by JanWerder** [comment]
Useful and very well documented, thanks. Would you do a PR?

**Comment by YoungNeer** [comment]
> Useful and very well documented, thanks. Would you do a PR?

Well I will. But at one go! I mean I am writing some other libraries at this stage which I believe are one of a kind. So a PR'd have to have till then. BTW Sorry for replying after 2 days. I didn't see this earlier.

**Comment by flamendless** [comment]
Your previous pr for your other lib wasn't accepted because it lacks documentation. You should make a pr only for clove right now.

**Comment by YoungNeer** [comment]
> Your previous pr for your other lib wasn't accepted because it lacks documentation. You should make a pr only for clove right now.

Well what about [iffy](https://github.com/YoungNeer/lovelib/tree/master/iffy)

**Comment by flamendless** [comment]
@YoungNeer you should make a separate PR for that. 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YoungNeer** [comment]
what's this travis-ci thing, brbl?? I don't understand

**Comment by flamendless** [comment]
It's kinda like a process that checks whether a PR can be merged without causing any issue like build fail and more.
