### ISSUE TITLE
Add flare

### ISSUE THREAD

**Issue by YoungNeer** [love2d-community/awesome-love2d#146]
I am not making a PR because i'm not sure which category would flare belong to. :confused:
(https://github.com/YoungNeer/lovelib/blob/master/flare)

**Comment by flamendless** [comment]
This should not be an issue. If you know what your lib does, im pretty sure you have an idea in what category it "can" be

**Comment by flamendless** [comment]
Hmmm looking at that lib, how do you "know" the progress for the progress bar?

**Comment by JanWerder** [comment]
From what I've read you have to know that upfront and pass it in the delay parameter. While this is technically a library, it doesn't really add any functionality, but only wraps a couple of Löve functions. So while there isn't a real definition what should be added to the list and what not, I would see this on the "what-not" side. Not that it isnt useful to you, but I don't think others should rely on a library for such a simple use-case.

**Comment by YoungNeer** [comment]
> Hmmm looking at that lib, how do you "know" the progress for the progress bar?

Well there's a built-in function for that - but you could over-ride it to set like how fast or how slow should the progress move at each frame). Please consider looking at the source-code - it's super easy to understand.

**Comment by YoungNeer** [comment]
I think you are -perhaps- not getting what I mean by splash-screen. Splash-screens mean seperate windows with different aspect ratio than the original. Please see this demo https://quickfileshare.org/1079/flareDemo.love (forgive the 60s wait)

**Comment by girng** [comment]
I would vote for `Helper Libraries`
