### ISSUE TITLE
Add ecs-lua

### ISSUE THREAD

**Issue by Jamtoad** [love2d-community/awesome-love2d#225]
ECS-Lua works in any engine that uses Lua and its pretty neat. Maybe include it here?

https://github.com/nidorx/ecs-lua

**Comment by premek** [comment]
i think lua libraries that does not require love but are helpful in gamedev should be included

**Comment by MikuAuahDark** [comment]
Sure thing then. Send a PR then I'll merge it right away.

**Comment by JanWerder** [comment]
Will add it, thanks.
