### ISSUE TITLE
Add "Resolution Solution"? 

### ISSUE THREAD

**Issue by Vovkiv** [love2d-community/awesome-love2d#230]
https://github.com/Vovkiv/resolution_solution

People often don't know how to handle resolution and scaling for their games, so this library solves this. It has 2 scaling methods: "Aspect Scaling" and stretching, which you can change seamlessly. It also has scaling related functions (for example, translating from/to scaled game area, check if cursor inside scaled area) and it can be easy adapted to other libraries which relies on scaling and translating, such as camera libs. Maybe it worth put here? Somewhere under "Drawing" section?

**Comment by MikuAuahDark** [comment]
Sure. Send a PR and I'll merge it.

**Comment by MikuAuahDark** [comment]
Added in #232.
