### ISSUE TITLE
Adding strike through to Deprecated/Abandoned/Deleted Entries

### ISSUE THREAD

**Issue by alejandro-alzate** [love2d-community/awesome-love2d#270]
For example: modern love negates ~~love-mimcrophone~~ ([Prove](https://love2d-community.github.io/love-api/#type_RecordingDevice))
and others were abandoned and no longer work on modern love.

So ~~stealing~~ *borrowing* typing hints standards from editors, that warns you about that you're using a legacy feature that may or may not either break or get removed.
![image_2024-10-07_20-27-10](https://github.com/user-attachments/assets/43e3ae23-0e2e-4f18-94e2-6269042286da)
But still allows to use it, and explains it's functionality.

**Comment by MikuAuahDark** [comment]
I believe this goes to love-api instead in awesome-love2d.

Regarding this, I don't think providing deprecated functions is a good idea. You can mark function as deprecated in LuaLS/sumneko but I think the outcome is not to provide deprecated functions at all for love-api.

**Comment by alejandro-alzate** [comment]
It is directed a both, on the awesome list just to let people know that a lib or tool has not been given some love for a while

**Comment by alejandro-alzate** [comment]
that pun was not intentional i swear.
