### ISSUE TITLE
Switch LUBE with Grease

### ISSUE THREAD

**Issue by Bobbyjoness** [love2d-community/awesome-love2d#46]
Lube has been updated and renamed to Grease. Probably would be best to have the most up to date version. (also a search friendly name lol)

**Comment by JanWerder** [comment]
Mhm, I don't find the repo for that. Could you point me to it?

**Comment by Bobbyjoness** [comment]
https://github.com/bartbes/love-misc-libs/tree/master/grease

**Comment by rm-code** [comment]
LUBE isn't on the list yet anyway, right?

**Comment by Bobbyjoness** [comment]
It is under networking.

**Comment by josefnpat** [comment]
:+1:
