### ISSUE TITLE
State switcher libraries

### ISSUE THREAD

**Issue by nekromoff** [love2d-community/awesome-love2d#72]
Hello,

I would like to add a section with state switching Love2D libraries, such as this (made long time ago by me): http://www.ambience.sk/love2d-a-state-switcher-class-lua/ 

Also mentioned in the wiki:
https://love2d.org/wiki/Stateswitcher

And there are few more useful simple libs like this for state switching.

**Comment by JanWerder** [comment]
There are multiple libraries like yours in the Helper Library section. Maybe we could make a new section out of it

**Comment by nekromoff** [comment]
If you think such simple, single purpose libraries could go into helpers, I am OK with that.

**Comment by JanWerder** [comment]
Oh, one more question? Do you have a github repo or anything similar for the code. A zip on your site, while not wrong, is more likely to cease existing than a free repo

**Comment by nekromoff** [comment]
I'll put it up on github and post the lik.

**Comment by nekromoff** [comment]
https://github.com/nekromoff/love-state-switcher

**Comment by nekromoff** [comment]
Hi, could you please include it? Thanks

**Comment by JanWerder** [comment]
Just added it
