### ISSUE TITLE
Include Sublime Text in IDE Section

### ISSUE THREAD

**Issue by flamendless** [love2d-community/awesome-love2d#75]
Please include [sublime text ](https://www.sublimetext.com/)

Plugin/Package Manager [here](https://packagecontrol.io/)

Love2D packages:
 [SublimeLove](https://packagecontrol.io/packages/SublimeLove)

**Comment by JanWerder** [comment]
Hey, could you prepare a pull-request with these links?

**Comment by flamendless** [comment]
Done?

**Comment by JanWerder** [comment]
Yup, are there any other plugins needed to develop for Löve in Sublime Text? i.e. a lua plugin?

**Comment by flamendless** [comment]
None, that SublimeLove already covers the basic needs for love2d

**Comment by JanWerder** [comment]
Okay, great :smiley:
