### ISSUE TITLE
Remove travis bot?

### ISSUE THREAD

**Issue by rm-code** [love2d-community/awesome-love2d#82]
@JanWerder It seems like we recently got more and more failed builds even though the links seem to be fine.

All the current PRs are failing due to some 301 or 500 errors.

I wonder if makes sense to keep the bot around still.

**Comment by JanWerder** [comment]
I looked into this and the 301 errors are right, I'll fix them in a moment. The 500 error is on sublimetext.com and I honestly got the same error on my second refresh in the browser, no idea what's going on there.

I think it works reasonably well and helps with keeping the document clean. I would rather want to expand it to check if the alphabetic order in the document is right :wink:  (Which is something I disregard more often than I'm willing to admit)

**Comment by JanWerder** [comment]
The latest commit turned out green again https://github.com/love2d-community/awesome-love2d/commit/a61e920e195a9e6fe026f9439497926ee58c6f83

:smiley:

**Comment by rm-code** [comment]
Aye ok my bad 😅  I thought the links were actually good :P
